CREATE TABLE products (
  ID INT NOT NULL AUTO_INCREMENT,
  reference VARCHAR(80) NOT NULL,
  title VARCHAR(255) NOT NULL,
  size VARCHAR(255) NOT NULL,
  price INT NOT NULL,
  page_url VARCHAR(255) NOT NULL,
  updated_on DATE DEFAULT (CURDATE()),
  PRIMARY KEY (ID)
) ENGINE=InnoDB;
